export interface Pais {
  nombre: string;
  iso2: string;
}

const PAISES_RAW: Pais[] = [
  { nombre: 'Afganistán', iso2: 'AF' },
  { nombre: 'Albania', iso2: 'AL' },
  { nombre: 'Alemania', iso2: 'DE' },
  { nombre: 'Andorra', iso2: 'AD' },
  { nombre: 'Angola', iso2: 'AO' },
  { nombre: 'Antigua y Barbuda', iso2: 'AG' },
  { nombre: 'Arabia Saudita', iso2: 'SA' },
  { nombre: 'Argelia', iso2: 'DZ' },
  { nombre: 'Argentina', iso2: 'AR' },
  { nombre: 'Armenia', iso2: 'AM' },
  { nombre: 'Australia', iso2: 'AU' },
  { nombre: 'Austria', iso2: 'AT' },
  { nombre: 'Azerbaiyán', iso2: 'AZ' },
  { nombre: 'Bahamas', iso2: 'BS' },
  { nombre: 'Bangladés', iso2: 'BD' },
  { nombre: 'Barbados', iso2: 'BB' },
  { nombre: 'Baréin', iso2: 'BH' },
  { nombre: 'Bélgica', iso2: 'BE' },
  { nombre: 'Belice', iso2: 'BZ' },
  { nombre: 'Benín', iso2: 'BJ' },
  { nombre: 'Bielorrusia', iso2: 'BY' },
  { nombre: 'Birmania (Myanmar)', iso2: 'MM' },
  { nombre: 'Bolivia', iso2: 'BO' },
  { nombre: 'Bosnia y Herzegovina', iso2: 'BA' },
  { nombre: 'Botsuana', iso2: 'BW' },
  { nombre: 'Brasil', iso2: 'BR' },
  { nombre: 'Brunéi', iso2: 'BN' },
  { nombre: 'Bulgaria', iso2: 'BG' },
  { nombre: 'Burkina Faso', iso2: 'BF' },
  { nombre: 'Burundi', iso2: 'BI' },
  { nombre: 'Bután', iso2: 'BT' },
  { nombre: 'Cabo Verde', iso2: 'CV' },
  { nombre: 'Camboya', iso2: 'KH' },
  { nombre: 'Camerún', iso2: 'CM' },
  { nombre: 'Canadá', iso2: 'CA' },
  { nombre: 'Catar', iso2: 'QA' },
  { nombre: 'Chad', iso2: 'TD' },
  { nombre: 'Chile', iso2: 'CL' },
  { nombre: 'China', iso2: 'CN' },
  { nombre: 'Chipre', iso2: 'CY' },
  { nombre: 'Ciudad del Vaticano', iso2: 'VA' },
  { nombre: 'Colombia', iso2: 'CO' },
  { nombre: 'Comoras', iso2: 'KM' },
  { nombre: 'Corea del Norte', iso2: 'KP' },
  { nombre: 'Corea del Sur', iso2: 'KR' },
  { nombre: 'Costa de Marfil', iso2: 'CI' },
  { nombre: 'Costa Rica', iso2: 'CR' },
  { nombre: 'Croacia', iso2: 'HR' },
  { nombre: 'Cuba', iso2: 'CU' },
  { nombre: 'Dinamarca', iso2: 'DK' },
  { nombre: 'Dominica', iso2: 'DM' },
  { nombre: 'Ecuador', iso2: 'EC' },
  { nombre: 'Egipto', iso2: 'EG' },
  { nombre: 'El Salvador', iso2: 'SV' },
  { nombre: 'Emiratos Árabes Unidos', iso2: 'AE' },
  { nombre: 'Eritrea', iso2: 'ER' },
  { nombre: 'Eslovaquia', iso2: 'SK' },
  { nombre: 'Eslovenia', iso2: 'SI' },
  { nombre: 'España', iso2: 'ES' },
  { nombre: 'Estados Unidos', iso2: 'US' },
  { nombre: 'Estonia', iso2: 'EE' },
  { nombre: 'Esuatini', iso2: 'SZ' },
  { nombre: 'Etiopía', iso2: 'ET' },
  { nombre: 'Filipinas', iso2: 'PH' },
  { nombre: 'Finlandia', iso2: 'FI' },
  { nombre: 'Fiyi', iso2: 'FJ' },
  { nombre: 'Francia', iso2: 'FR' },
  { nombre: 'Gabón', iso2: 'GA' },
  { nombre: 'Gambia', iso2: 'GM' },
  { nombre: 'Georgia', iso2: 'GE' },
  { nombre: 'Ghana', iso2: 'GH' },
  { nombre: 'Granada', iso2: 'GD' },
  { nombre: 'Grecia', iso2: 'GR' },
  { nombre: 'Guatemala', iso2: 'GT' },
  { nombre: 'Guinea', iso2: 'GN' },
  { nombre: 'Guinea-Bisáu', iso2: 'GW' },
  { nombre: 'Guinea Ecuatorial', iso2: 'GQ' },
  { nombre: 'Guyana', iso2: 'GY' },
  { nombre: 'Haití', iso2: 'HT' },
  { nombre: 'Honduras', iso2: 'HN' },
  { nombre: 'Hungría', iso2: 'HU' },
  { nombre: 'India', iso2: 'IN' },
  { nombre: 'Indonesia', iso2: 'ID' },
  { nombre: 'Irak', iso2: 'IQ' },
  { nombre: 'Irán', iso2: 'IR' },
  { nombre: 'Irlanda', iso2: 'IE' },
  { nombre: 'Islandia', iso2: 'IS' },
  { nombre: 'Islas Marshall', iso2: 'MH' },
  { nombre: 'Islas Salomón', iso2: 'SB' },
  { nombre: 'Israel', iso2: 'IL' },
  { nombre: 'Italia', iso2: 'IT' },
  { nombre: 'Jamaica', iso2: 'JM' },
  { nombre: 'Japón', iso2: 'JP' },
  { nombre: 'Jordania', iso2: 'JO' },
  { nombre: 'Kazajistán', iso2: 'KZ' },
  { nombre: 'Kenia', iso2: 'KE' },
  { nombre: 'Kirguistán', iso2: 'KG' },
  { nombre: 'Kiribati', iso2: 'KI' },
  { nombre: 'Kuwait', iso2: 'KW' },
  { nombre: 'Laos', iso2: 'LA' },
  { nombre: 'Lesoto', iso2: 'LS' },
  { nombre: 'Letonia', iso2: 'LV' },
  { nombre: 'Líbano', iso2: 'LB' },
  { nombre: 'Liberia', iso2: 'LR' },
  { nombre: 'Libia', iso2: 'LY' },
  { nombre: 'Liechtenstein', iso2: 'LI' },
  { nombre: 'Lituania', iso2: 'LT' },
  { nombre: 'Luxemburgo', iso2: 'LU' },
  { nombre: 'Macedonia del Norte', iso2: 'MK' },
  { nombre: 'Madagascar', iso2: 'MG' },
  { nombre: 'Malasia', iso2: 'MY' },
  { nombre: 'Malaui', iso2: 'MW' },
  { nombre: 'Maldivas', iso2: 'MV' },
  { nombre: 'Malí', iso2: 'ML' },
  { nombre: 'Malta', iso2: 'MT' },
  { nombre: 'Marruecos', iso2: 'MA' },
  { nombre: 'Mauricio', iso2: 'MU' },
  { nombre: 'Mauritania', iso2: 'MR' },
  { nombre: 'México', iso2: 'MX' },
  { nombre: 'Micronesia', iso2: 'FM' },
  { nombre: 'Moldavia', iso2: 'MD' },
  { nombre: 'Mónaco', iso2: 'MC' },
  { nombre: 'Mongolia', iso2: 'MN' },
  { nombre: 'Montenegro', iso2: 'ME' },
  { nombre: 'Mozambique', iso2: 'MZ' },
  { nombre: 'Namibia', iso2: 'NA' },
  { nombre: 'Nauru', iso2: 'NR' },
  { nombre: 'Nepal', iso2: 'NP' },
  { nombre: 'Nicaragua', iso2: 'NI' },
  { nombre: 'Níger', iso2: 'NE' },
  { nombre: 'Nigeria', iso2: 'NG' },
  { nombre: 'Noruega', iso2: 'NO' },
  { nombre: 'Nueva Zelanda', iso2: 'NZ' },
  { nombre: 'Omán', iso2: 'OM' },
  { nombre: 'Países Bajos', iso2: 'NL' },
  { nombre: 'Pakistán', iso2: 'PK' },
  { nombre: 'Palaos', iso2: 'PW' },
  { nombre: 'Palestina', iso2: 'PS' },
  { nombre: 'Panamá', iso2: 'PA' },
  { nombre: 'Papúa Nueva Guinea', iso2: 'PG' },
  { nombre: 'Paraguay', iso2: 'PY' },
  { nombre: 'Perú', iso2: 'PE' },
  { nombre: 'Polonia', iso2: 'PL' },
  { nombre: 'Portugal', iso2: 'PT' },
  { nombre: 'Reino Unido', iso2: 'GB' },
  { nombre: 'República Centroafricana', iso2: 'CF' },
  { nombre: 'República Checa', iso2: 'CZ' },
  { nombre: 'República del Congo', iso2: 'CG' },
  { nombre: 'República Democrática del Congo', iso2: 'CD' },
  { nombre: 'República Dominicana', iso2: 'DO' },
  { nombre: 'Ruanda', iso2: 'RW' },
  { nombre: 'Rumania', iso2: 'RO' },
  { nombre: 'Rusia', iso2: 'RU' },
  { nombre: 'Samoa', iso2: 'WS' },
  { nombre: 'San Cristóbal y Nieves', iso2: 'KN' },
  { nombre: 'San Marino', iso2: 'SM' },
  { nombre: 'San Vicente y las Granadinas', iso2: 'VC' },
  { nombre: 'Santa Lucía', iso2: 'LC' },
  { nombre: 'Santo Tomé y Príncipe', iso2: 'ST' },
  { nombre: 'Senegal', iso2: 'SN' },
  { nombre: 'Serbia', iso2: 'RS' },
  { nombre: 'Seychelles', iso2: 'SC' },
  { nombre: 'Sierra Leona', iso2: 'SL' },
  { nombre: 'Singapur', iso2: 'SG' },
  { nombre: 'Siria', iso2: 'SY' },
  { nombre: 'Somalia', iso2: 'SO' },
  { nombre: 'Sri Lanka', iso2: 'LK' },
  { nombre: 'Sudáfrica', iso2: 'ZA' },
  { nombre: 'Sudán', iso2: 'SD' },
  { nombre: 'Sudán del Sur', iso2: 'SS' },
  { nombre: 'Suecia', iso2: 'SE' },
  { nombre: 'Suiza', iso2: 'CH' },
  { nombre: 'Surinam', iso2: 'SR' },
  { nombre: 'Tailandia', iso2: 'TH' },
  { nombre: 'Tanzania', iso2: 'TZ' },
  { nombre: 'Tayikistán', iso2: 'TJ' },
  { nombre: 'Timor Oriental', iso2: 'TL' },
  { nombre: 'Togo', iso2: 'TG' },
  { nombre: 'Tonga', iso2: 'TO' },
  { nombre: 'Trinidad y Tobago', iso2: 'TT' },
  { nombre: 'Túnez', iso2: 'TN' },
  { nombre: 'Turkmenistán', iso2: 'TM' },
  { nombre: 'Turquía', iso2: 'TR' },
  { nombre: 'Tuvalu', iso2: 'TV' },
  { nombre: 'Ucrania', iso2: 'UA' },
  { nombre: 'Uganda', iso2: 'UG' },
  { nombre: 'Uruguay', iso2: 'UY' },
  { nombre: 'Uzbekistán', iso2: 'UZ' },
  { nombre: 'Vanuatu', iso2: 'VU' },
  { nombre: 'Venezuela', iso2: 'VE' },
  { nombre: 'Vietnam', iso2: 'VN' },
  { nombre: 'Yemen', iso2: 'YE' },
  { nombre: 'Yibuti', iso2: 'DJ' },
  { nombre: 'Zambia', iso2: 'ZM' },
  { nombre: 'Zimbabue', iso2: 'ZW' },
];

// Lista estable, ordenada alfabéticamente en español (independiente del orden de carga arriba).
export const PAISES: Pais[] = [...PAISES_RAW].sort((a, b) => a.nombre.localeCompare(b.nombre, 'es'));

export function normalizarTextoPais(s: string): string {
  return s.trim().toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '');
}

export function buscarPaises(query: string): Pais[] {
  const norm = normalizarTextoPais(query);
  if (!norm) return PAISES;
  return PAISES.filter((p) => normalizarTextoPais(p.nombre).includes(norm));
}

export function getPaisPorIso2(iso2: string): Pais | undefined {
  return PAISES.find((p) => p.iso2 === iso2);
}
